(global-auto-revert-mode 1)
(setq make-backup-files nil)
(setq auto-save-default nil)
(menu-bar-mode 0)
(setq scroll-step 1)
(setq inhibit-splash-screen t)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq next-line-add-newlines nil)
(setq mouse-wheel-progressive-speed nil)
(setq scroll-conservatively 10000)
(setq scroll-preserve-screen-position 1)
(setq next-screen-context-lines 33)
(add-hook 'before-save-hook 'delete-trailing-whitespace)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 8)
(setq-default c-default-style "linux")
(setq-default buffer-file-coding-system 'utf-8-unix)
(setq default-buffer-file-coding-system 'utf-8-unix)
(setq initial-major-mode 'fundamental-mode)
(setq initial-scratch-message nil)
(setq line-move-visual nil)
(global-set-key (kbd "C-c p") 'find-lisp-find-dired)
;; reference: https://emacs.stackexchange.com/questions/21651
(defun b0h-reasonable-window-split (&optional window)
  (cond
   ((and (> (window-width window)
            (window-height window))
         (window-splittable-p window 'horizontal))
    (with-selected-window window
      (split-window-right)))
   ((window-splittable-p window)
    (with-selected-window window
      (split-window-below)))))
(setq split-window-preferred-function #'b0h-reasonable-window-split)
(setq b0h-saved-point-line nil)
(setq b0h-saved-point-column nil)
(defun b0h-save-point ()
  (interactive)
  (progn
    (setq b0h-saved-point-line (- (line-number-at-pos) 1))
    (setq b0h-saved-point-column (- (point) (line-beginning-position)))))
(defun b0h-load-point ()
  (interactive)
  (if b0h-saved-point-line
      (if b0h-saved-point-column
          (progn
            (goto-char (point-min))
            (ignore-errors (forward-line b0h-saved-point-line))
            (ignore-errors (forward-char b0h-saved-point-column))
            (if (/= b0h-saved-point-line (- (line-number-at-pos) 1))
                (progn
                  (goto-char (point-min))
                  (ignore-errors (forward-line b0h-saved-point-line))
                  (move-end-of-line nil)))))))
;; check "M-x find-function shell-command-on-region" for details
(defun b0h-format-file (command)
  (interactive (list (read-shell-command "Shell command: ")))
  (b0h-save-point)
  (call-process-region (point-min) (point-max) shell-file-name t t nil shell-command-switch command)
  (b0h-load-point)
  (recenter-top-bottom))
(setq b0h-highlights (make-hash-table :test 'equal))
(defun b0h-toggle-highlight-at-point ()
  (interactive)
  (save-excursion
    (let ((default-hi-lock-auto-select-face-value hi-lock-auto-select-face)
          (default-case-fold-search-value case-fold-search))
      (setq hi-lock-auto-select-face t)
      (setq case-fold-search nil)
      (if (looking-at "[[:alnum:]_]")
          (progn
            (search-forward-regexp "\\_>")
            (let ((end (point)))
              (search-backward-regexp "\\_<")
              (let ((symbol-regexp (concat "\\_<" (buffer-substring (point) end) "\\_>")))
                (if (gethash symbol-regexp b0h-highlights)
                    (progn
                      (remhash symbol-regexp b0h-highlights)
                      (unhighlight-regexp symbol-regexp))
                  (progn
                    (puthash symbol-regexp t b0h-highlights)
                    (highlight-regexp symbol-regexp (hi-lock-read-face-name))))))))
      (setq hi-lock-auto-select-face default-hi-lock-auto-select-face-value)
      (setq case-fold-search default-case-fold-search-value))))
(global-set-key (kbd "C-c Ω a") 'b0h-toggle-highlight-at-point)
(define-key key-translation-map (kbd "TAB") (kbd "M-/"))
(define-key key-translation-map (kbd "M-/") (kbd "TAB"))
(define-key key-translation-map (kbd "C-t") (kbd "C-c Ω a"))
(define-key key-translation-map (kbd "C-z") (kbd "TAB"))
(add-hook 'minibuffer-setup-hook
          (lambda ()
            (define-key key-translation-map (kbd "TAB") (kbd "TAB"))
            (define-key key-translation-map (kbd "M-/") (kbd "M-/"))
            (define-key key-translation-map (kbd "C-t") (kbd "C-t"))))
(add-hook 'minibuffer-exit-hook
          (lambda ()
            (define-key key-translation-map (kbd "TAB") (kbd "M-/"))
            (define-key key-translation-map (kbd "M-/") (kbd "TAB"))
            (define-key key-translation-map (kbd "C-t") (kbd "C-c Ω a"))))
(setq isearch-lazy-count t)
(fido-mode 1)
(fido-vertical-mode 1)
(set-background-color "#FFFFE1")
(blink-cursor-mode 0)
(global-hl-line-mode 1)
(set-face-background hl-line-face "#F0F0D3")
(define-key key-translation-map (kbd "C-o") (kbd "C-x o"))
(define-key key-translation-map (kbd "C-x o") (kbd "C-o"))
(setq column-number-mode t)
