(deftheme b0h-light "B0H Light Theme")

(setq b0h-theme-text-color "SystemWindowText")
(setq b0h-theme-background-color "#FFFFD7")
(setq b0h-theme-line-highlight-color "#F3F3CC")
(setq b0h-theme-cursor-color "#F00279")
(setq b0h-theme-keyword-color "#0022C9")
(setq b0h-theme-string-color "#6E0000")
(setq b0h-theme-comment-color "#015400")
(setq b0h-theme-region-color "#D7FFDE")
(setq b0h-theme-search-highlight-color "#7AA4FF")
(setq b0h-theme-lsp-symbol-highlight-color "#BAF7C5")
(setq b0h-theme-mode-line-inactive-color "#D7FFFF")
(setq b0h-theme-mode-line-active-color "#D7AFFF")
(setq b0h-theme-fringe-color "#F2F2D3")
(setq b0h-theme-dired-directory-color "#007A00")

(custom-theme-set-faces
 'b0h-light
 `(cursor ((t (:background ,b0h-theme-cursor-color))))
 `(default ((t (:background ,b0h-theme-background-color :foreground ,b0h-theme-text-color))))
 `(hl-line ((t (:background ,b0h-theme-line-highlight-color))))
 `(font-lock-builtin-face ((t (:foreground ,b0h-theme-keyword-color))))
 `(font-lock-comment-delimiter-face ((t (:foreground ,b0h-theme-comment-color))))
 `(font-lock-comment-face ((t (:foreground ,b0h-theme-comment-color))))
 `(font-lock-constant-face ((t (:foreground ,b0h-theme-text-color))))
 `(font-lock-doc-face ((t (:foreground ,b0h-theme-comment-color))))
 `(font-lock-doc-markup-face ((t (:foreground ,b0h-theme-comment-color))))
 `(font-lock-function-name-face ((t (:foreground ,b0h-theme-text-color))))
 `(font-lock-keyword-face ((t (:foreground ,b0h-theme-keyword-color))))
 `(font-lock-negation-char-face ((t (:foreground ,b0h-theme-text-color))))
 `(font-lock-preprocessor-face ((t (:foreground ,b0h-theme-keyword-color))))
 `(font-lock-string-face ((t (:foreground ,b0h-theme-string-color))))
 `(font-lock-type-face ((t (:foreground ,b0h-theme-text-color))))
 `(font-lock-variable-name-face ((t (:foreground ,b0h-theme-text-color))))
 `(region ((t (:background ,b0h-theme-region-color))))
 `(lazy-highlight ((t (:background ,b0h-theme-search-highlight-color))))
 `(mode-line-inactive ((t (:inherit mode-line :background ,b0h-theme-mode-line-inactive-color))))
 `(mode-line-active ((t (:inherit mode-line :background ,b0h-theme-mode-line-active-color))))
 `(fringe ((t (:background ,b0h-theme-fringe-color))))
 `(dired-directory ((t (:foreground ,b0h-theme-dired-directory-color))))
 `(eglot-highlight-symbol-face ((t (:background ,b0h-theme-lsp-symbol-highlight-color :weight 'normal)))))

(provide-theme 'b0h-light)
